language: python
python:
    - "3.6"
addons:
    postgresql: "9.6"
env:
  - APP_SETTINGS="config.DevelopmentConfig"
  - FLASK_APP=edenthegame.py
  - DATABASE_URL="postgresql://localhost/edendata"
script:
    - python test_app.py
