version: '2.2'

services:
   postgres:
      restart: always
      image: postgres:latest
      environment:
         - POSTGRES_USER=zagan
         - POSTGRES-PASSWORD=sekongo
         - POSTGRES_DB=edendata
      volumes:
         - ./edendata/postgres:/var/lib/postgresql/data
      ports:
         - "5432:5432"
   app:
      restart: always
      build: .
      ports:
            - 80:5000
      volumes:
         - .:/tmp

networks:
   default:
      external:
         name: eden-net
