"""empty message

Revision ID: 0b7782690b0a
Revises: 5411c03d6267
Create Date: 2018-06-25 17:09:17.670667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7782690b0a'
down_revision = '5411c03d6267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profils_name', table_name='profils')
    op.drop_index('ix_profils_value', table_name='profils')
    op.drop_column('profils', 'value')
    op.drop_column('profils', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('profils', sa.Column('value', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.create_index('ix_profils_value', 'profils', ['value'], unique=True)
    op.create_index('ix_profils_name', 'profils', ['name'], unique=True)
    # ### end Alembic commands ###
