"""empty message

Revision ID: 3f505406bb1b
Revises: 9f4bae5a71ef
Create Date: 2018-06-25 18:53:31.309873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f505406bb1b'
down_revision = '9f4bae5a71ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('caracteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('profils', 'caracterics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('caracterics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('profils', 'caracteristics')
    # ### end Alembic commands ###
