"""empty message

Revision ID: 5411c03d6267
Revises: 
Create Date: 2018-06-21 22:23:10.469628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5411c03d6267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacite', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipement', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_name'), 'factions', ['name'], unique=True)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiltype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiltype_name'), 'profiltype', ['name'], unique=True)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_description'), 'states', ['description'], unique=True)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('stigmates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stigmates_name'), 'stigmates', ['name'], unique=True)
    op.create_table('tactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tactique', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=8), nullable=True),
    sa.Column('caractéristiques', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('stigmate_id', sa.Integer(), nullable=True),
    sa.Column('profiltype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.ForeignKeyConstraint(['profiltype_id'], ['profiltype.id'], ),
    sa.ForeignKeyConstraint(['stigmate_id'], ['stigmates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profils_name'), 'profils', ['name'], unique=True)
    op.create_index(op.f('ix_profils_value'), 'profils', ['value'], unique=True)
    op.create_table('profils_capacites',
    sa.Column('profils_id', sa.Integer(), nullable=True),
    sa.Column('capacites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capacites_id'], ['capacites.id'], ),
    sa.ForeignKeyConstraint(['profils_id'], ['profils.id'], )
    )
    op.create_table('profils_equipements',
    sa.Column('profils_id', sa.Integer(), nullable=True),
    sa.Column('equipements_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipements_id'], ['equipements.id'], ),
    sa.ForeignKeyConstraint(['profils_id'], ['profils.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profils_equipements')
    op.drop_table('profils_capacites')
    op.drop_index(op.f('ix_profils_value'), table_name='profils')
    op.drop_index(op.f('ix_profils_name'), table_name='profils')
    op.drop_table('profils')
    op.drop_table('tactics')
    op.drop_index(op.f('ix_stigmates_name'), table_name='stigmates')
    op.drop_table('stigmates')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_description'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_profiltype_name'), table_name='profiltype')
    op.drop_table('profiltype')
    op.drop_table('missions')
    op.drop_index(op.f('ix_factions_name'), table_name='factions')
    op.drop_table('factions')
    op.drop_table('equipements')
    op.drop_table('capacites')
    # ### end Alembic commands ###
