"""first migration

Revision ID: 8e13948331e9
Revises: 
Create Date: 2018-06-20 18:07:11.173855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e13948331e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_name'), 'factions', ['name'], unique=True)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_description'), 'states', ['description'], unique=True)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('stigmates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stigmates_name'), 'stigmates', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stigmates_name'), table_name='stigmates')
    op.drop_table('stigmates')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_description'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_factions_name'), table_name='factions')
    op.drop_table('factions')
    # ### end Alembic commands ###
