"""empty message

Revision ID: 9f4bae5a71ef
Revises: 0b7782690b0a
Create Date: 2018-06-25 18:49:38.363595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f4bae5a71ef'
down_revision = '0b7782690b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('caracterics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('profils', 'caractéristiques')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profils', sa.Column('caractéristiques', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('profils', 'caracterics')
    # ### end Alembic commands ###
