"""empty message

Revision ID: f36cfb087787
Revises: 3915841292d8
Create Date: 2018-06-29 15:04:52.094439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36cfb087787'
down_revision = '3915841292d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profils_capacites')
    op.drop_table('profils_equipements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profils_equipements',
    sa.Column('profils_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipements_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipements_id'], ['equipements.id'], name='profils_equipements_equipements_id_fkey'),
    sa.ForeignKeyConstraint(['profils_id'], ['profils.id'], name='profils_equipements_profils_id_fkey')
    )
    op.create_table('profils_capacites',
    sa.Column('profils_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capacites_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['capacites_id'], ['capacites.id'], name='profils_capacites_capacites_id_fkey'),
    sa.ForeignKeyConstraint(['profils_id'], ['profils.id'], name='profils_capacites_profils_id_fkey')
    )
    # ### end Alembic commands ###
